### ISSUE TITLE
librealsense ebuild

### ISSUE THREAD

**Issue by haschka** [NP-Hardass/np-hardass-overlay#2]
Hi I used your librealsense ebuild to install it on my gentoo system. 

You forgot to move the header files to include so that anyone building stuff on librealsens can do it. Without the header files one can use librealsens but not compile new programs using it, which is just what I do. 

I fixed this by putting the following additional lines into the ebuilds src_install, you might want to update your ebuild. Maybe there is a better way to do this and move the whole folder, i.e. if in future releases more header files are to come.. 
    insinto /usr/include/librealsense/
    doins include/librealsense/rs.h
    doins include/librealsense/rs.hpp
    doins include/librealsense/rsutil.h

cheers, 
- Thomas

**Comment by NP-Hardass** [comment]
Hey,

Was having issues with github email notifications back when you posted this and missed seeing it.

I've just push an update which includes the header files.  Thanks for letting me know.
